// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts,import_extension="
// @generated from file greeting/v1/service.proto (package greeting.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetRequest, GreetResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greeting.v1.GreetService
 */
export const GreetService = {
  typeName: "greeting.v1.GreetService",
  methods: {
    /**
     * @generated from rpc greeting.v1.GreetService.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

