// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts,import_extension="
// @generated from file prompt/v1/service.proto (package prompt.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CreatePromptRequest, CreatePromptResponse, GetPromptRequest, GetPromptResponse, GetPromptValueRequest, GetPromptValueResponse, ListPromptsResponse } from "./service_pb";

/**
 * @generated from service prompt.v1.PromptRegistryService
 */
export const PromptRegistryService = {
  typeName: "prompt.v1.PromptRegistryService",
  methods: {
    /**
     * Prompt managment
     *
     * @generated from rpc prompt.v1.PromptRegistryService.ListPrompts
     */
    listPrompts: {
      name: "ListPrompts",
      I: Empty,
      O: ListPromptsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc prompt.v1.PromptRegistryService.CreatePrompt
     */
    createPrompt: {
      name: "CreatePrompt",
      I: CreatePromptRequest,
      O: CreatePromptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc prompt.v1.PromptRegistryService.GetPrompt
     */
    getPrompt: {
      name: "GetPrompt",
      I: GetPromptRequest,
      O: GetPromptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc prompt.v1.PromptRegistryService.GetPromptValue
     */
    getPromptValue: {
      name: "GetPromptValue",
      I: GetPromptValueRequest,
      O: GetPromptValueResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

