FROM golang:1.21-alpine3.18 as builder
RUN mkdir /workspace

WORKDIR /workspace
COPY ./mobius ./mobius
COPY ./protos ./protos
COPY ./worker ./worker

COPY ./go.work .
RUN go work sync

WORKDIR /workspace/mobius
RUN cgo_enabled=0 goos=linux go build -o bin/mobius


FROM alpine:3.18
COPY --from=builder /workspace/mobius/bin/mobius /usr/bin/
RUN apk update
RUN apk add ca-certificates


# glibc compatibility library, since go binaries 
# don't work well with musl libc that alpine uses
RUN apk add libc6-compat

ENTRYPOINT ["mobius"]