FROM golang:1.21-alpine3.18 as builder
RUN apk add make
RUN GO111MODULE=on GOBIN=/usr/local/bin go install \
github.com/bufbuild/buf/cmd/buf@v1.29.0
RUN mkdir /workspace

WORKDIR /workspace
COPY ./gateway ./gateway
COPY ./protos ./protos
COPY ./worker ./worker
COPY ./common ./common

COPY ./go.work .
RUN go work sync

WORKDIR /workspace/gateway
RUN make build


FROM alpine:3.18
COPY --from=builder /workspace/gateway/bin/gateway /usr/bin/
RUN apk update
RUN apk add ca-certificates


# glibc compatibility library, since go binaries 
# don't work well with musl libc that alpine uses
RUN apk add libc6-compat

ENTRYPOINT ["gateway", "server"]