// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts,import_extension="
// @generated from file llm/service.proto (package llm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CompletionRequest, CompletionResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service llm.v1.LLMService
 */
export const LLMService = {
  typeName: "llm.v1.LLMService",
  methods: {
    /**
     * @generated from rpc llm.v1.LLMService.ChatCompletions
     */
    chatCompletions: {
      name: "ChatCompletions",
      I: CompletionRequest,
      O: CompletionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc llm.v1.LLMService.StreamChatCompletions
     */
    streamChatCompletions: {
      name: "StreamChatCompletions",
      I: CompletionRequest,
      O: CompletionResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

